<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembler">
      <HintPath>..\risc-v-utils\Assembler\bin\Debug\net8.0\Assembler.dll</HintPath>
    </Reference>
    <Reference Include="LibCPU">
      <HintPath>..\risc-v-utils\LibCPU\bin\Debug\net8.0\LibCPU.dll</HintPath>
    </Reference>
    <Reference Include="LibUtils">
      <HintPath>..\risc-v-utils\LibUtil\bin\Debug\net8.0\LibUtils.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>